---
styleguide: plataformatec/linters
engines:
  fixme:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- testdata

