package cmd

import (
	"github.com/GeertJohan/go.rice/embedded"
	"time"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    `CHANGELOG.md.tmpl`,
		FileModTime: time.Unix(1526266645, 0),
		Content:     string("# CHANGELOG\n\n{{range . -}}\n## [{{ .Name}}]({{ .RefURL }}) ({{ .Date.Format \"2006-01-02\" }})\n{{ if .Enhancements -}}\n### Implemented Enhancements\n{{ range .Enhancements }}\n* [#{{ .Number }}]({{ .HTMLURL }}) - {{.Title}}\n{{ end -}}\n{{ end -}}\n{{ if .Bugs }}\n### Fixed Bugs\n{{ range .Bugs}}\n* [#{{ .Number }}]({{ .HTMLURL }}) - {{.Title}}\n{{ end }}\n{{ end }}\n{{ if .ClosedIssues }}\n### Closed Issues\n{{ range .ClosedIssues }}\n* [#{{ .Number }}]({{ .HTMLURL }}) - {{.Title}}\n{{ end }}\n{{ end }}\n{{ end -}}\n\n\n*This changelog was automatically generated by [bowie](https://github.com/mattstratton/bowie)*"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   ``,
		DirModTime: time.Unix(1507943972, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // CHANGELOG.md.tmpl

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`../templates`, &embedded.EmbeddedBox{
		Name: `../templates`,
		Time: time.Unix(1507943972, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"CHANGELOG.md.tmpl": file2,
		},
	})
}
